# train.py: Script for training a model using the dataset generated by the previous script.
# This script takes arguments to specify the dataset and other configurations.

import json
import os
import pickle
from datetime import datetime
from pathlib import Path

import hydra
import pandas as pd
import torch
import torch.distributed as dist
import wandb
from dotenv import load_dotenv
from omegaconf import DictConfig, OmegaConf
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed

# all supported methods
from evaluate import run_eval
from hypersteer import get_model
from hypersteer.training import Trainer
from hypersteer.utils.configs import ExperimentConfig, config_to_pydantic
from hypersteer.utils.constants import (
    EMPTY_CONCEPT,
    METADATA_FILE,
    STATE_FILE,
)
from hypersteer.utils.helpers import (
    configure_tokenizer_model,
    destroy_process_group,
    get_and_set_device,
    get_logger,
    get_rank,
    get_world_size,
    setup_file_logging,
)
from hypersteer.utils.model_utils import get_suffix_length
from inference import run_inference

# Initialize the logger
logger = get_logger(__name__)


def data_generator(data_dir, held_out_concept_ids=None, select_concept_ids=None):
    """Generator function to read multiple data files and yield data subsets by concept_id.
    Processes files in order: train_data.parquet, train_data_0.parquet, train_data_1.parquet, etc.

    Args:
        data_dir (str): Path to the data directory.
        held_out_concept_ids (list[int]): List of concept_ids to exclude from the dataset.
        select_concept_ids (list[int]): List of concept_ids to select from the dataset.

    Yields:
        (concept_id, df_subset): A tuple containing the concept_id and subset DataFrame.

    """
    # Gather all file paths in the directory
    file_paths = [
        os.path.join(data_dir, f)
        for f in os.listdir(data_dir)
        if f.startswith("train_data") and f.endswith(".parquet") and "combined" not in f
    ]

    # Sort files: 'train_data.parquet' comes first, then 'train_data_X.parquet' sorted by X
    def extract_index(file_name):
        if file_name == "train_data.parquet":
            return -1  # Ensure 'train_data.parquet' comes first
        # Extract the number X from 'train_data_X.parquet'
        return int(file_name.split("_")[-1].split(".")[0])

    file_paths.sort(key=lambda x: extract_index(os.path.basename(x)))

    for file_path in file_paths:
        df = pd.read_parquet(file_path)
        concept_ids = df["concept_id"].unique()
        concept_ids.sort()
        for concept_id in concept_ids:
            _valid_concept = (
                (concept_id in select_concept_ids)
                if select_concept_ids
                else (
                    not held_out_concept_ids or concept_id not in held_out_concept_ids
                )
            )
            if concept_id >= 0 and (_valid_concept):
                # print(f"Processing concept_id {concept_id}")
                df_subset = df[df["concept_id"] == concept_id]
                yield (concept_id, df_subset)


def load_metadata(metadata_path):
    """Load metadata from a JSON lines file."""
    metadata = []
    with open(metadata_path) as f:
        for line in f:
            data = json.loads(line)
            metadata += [data]  # Return the metadata as is
    return metadata


def prepare_df(
    df_list,
    negative_df,
    metadata,
    tokenizer,
    binarize=False,
    train_on_negative=False,
    train_across_concepts=False,
    output_length=None,
    model_name=None,
    max_num_of_examples=None,
    hypernet_mode=False,
    replace_negative_description=True,
    negative_example_ratio=1,
):
    """Process a list of concept dataframes and return a combined dataframe.

    Args:
        df_list: List of (concept_id, concept_df) tuples
        negative_df: DataFrame containing negative examples
        metadata: List of metadata dictionaries indexed by concept_id
        tokenizer: Tokenizer instance
        binarize: Whether to binarize the dataset
        train_on_negative: Whether to include negative examples in training
        train_across_concepts: Whether to train across concepts
        output_length: Output length for chat models
        model_name: Name of the model
        max_num_of_examples: Maximum number of examples per concept
        hypernet_mode: Whether in hypernetwork mode
        replace_negative_description: Whether to replace negative descriptions
        negative_example_ratio: Ratio of negative to positive examples

    Returns:
        Combined DataFrame ready for training
    """
    from hypersteer.utils.constants import CHAT_MODELS

    suffix_length, suffix_str = get_suffix_length(tokenizer)
    is_chat_model = model_name in CHAT_MODELS if model_name else False
    all_dfs = []

    for concept_id, original_df in df_list:
        concept = metadata[concept_id]["concept"]
        genre = metadata[concept_id]["concept_genres_map"][concept][0]

        # assign input and output containing concept with 1, otherwise 0
        positive_df = original_df[
            (original_df["output_concept"] == concept)
            & (original_df["category"] == "positive")
        ]
        concept_negative_df = negative_df[(negative_df["concept_genre"] == genre)]

        if max_num_of_examples and max_num_of_examples > 0:
            positive_df = positive_df.head(max_num_of_examples // 2)
            concept_negative_df = concept_negative_df.head(max_num_of_examples // 2)

        if negative_example_ratio is not None:
            positive_example_per_concept = len(positive_df) // len(
                positive_df["output_concept"].unique()
            )
            negative_example_per_concept = int(
                positive_example_per_concept * negative_example_ratio
            )

            negative_dfs = []
            for concept_id_inner in positive_df["concept_id"].unique():
                concept_description = positive_df[
                    positive_df["concept_id"] == concept_id_inner
                ]["output_concept"].values[0]

                # Randomly sample negative examples for each concept from negative_df
                # and replace the description with the positive one.
                sampled_negative_df = concept_negative_df[
                    concept_negative_df["output_concept"] == EMPTY_CONCEPT
                ].sample(n=min(negative_example_per_concept, len(concept_negative_df)))
                sampled_negative_df = sampled_negative_df.copy()

                if replace_negative_description:
                    sampled_negative_df["output_concept"] = concept_description
                    sampled_negative_df["concept_id"] = concept_id_inner

                negative_dfs.append(sampled_negative_df)

            if negative_dfs:
                concept_negative_df = pd.concat(negative_dfs, axis=0, ignore_index=True)
                # shuffle the negative examples
                concept_negative_df = concept_negative_df.sample(frac=1).reset_index(
                    drop=True
                )

        if binarize:
            if is_chat_model:
                if model_name == "meta-llama/Llama-3.1-8B-Instruct":

                    def apply_chat_template(row):
                        messages = [
                            {
                                "role": "system",
                                "content": "You are a helpful assistant.",
                            },
                            {"role": "user", "content": row["input"]},
                            {"role": "assistant", "content": row["output"]},
                        ]
                        nobos = tokenizer.apply_chat_template(
                            messages,
                            tokenize=True,
                            add_generation_prompt=True,
                        )[1:-suffix_length]
                        return tokenizer.decode(nobos)

                    positive_df = positive_df.copy()
                    concept_negative_df = concept_negative_df.copy()
                    positive_df["combined"] = positive_df.apply(
                        apply_chat_template, axis=1
                    )
                    concept_negative_df["combined"] = concept_negative_df.apply(
                        apply_chat_template, axis=1
                    )
                else:

                    def apply_chat_template(row):
                        messages = [
                            {"role": "user", "content": row["input"]},
                            {"role": "assistant", "content": row["output"]},
                        ]
                        nobos = tokenizer.apply_chat_template(
                            messages,
                            tokenize=True,
                            add_generation_prompt=True,
                        )[1:-suffix_length]
                        return tokenizer.decode(nobos)

                    positive_df = positive_df.copy()
                    concept_negative_df = concept_negative_df.copy()
                    positive_df["combined"] = positive_df.apply(
                        apply_chat_template, axis=1
                    )
                    concept_negative_df["combined"] = concept_negative_df.apply(
                        apply_chat_template, axis=1
                    )
            else:
                positive_df = positive_df.copy()
                concept_negative_df = concept_negative_df.copy()
                positive_df["combined"] = positive_df["input"] + positive_df["output"]
                concept_negative_df["combined"] = (
                    concept_negative_df["input"] + concept_negative_df["output"]
                )

            positive_df = pd.DataFrame(positive_df[["combined"]]).rename(
                columns={"combined": "input"},
            )
            concept_negative_df = pd.DataFrame(
                concept_negative_df[["combined"]]
            ).rename(
                columns={"combined": "input"},
            )
            positive_df["labels"] = 1
            concept_negative_df["labels"] = 0
            concept_df = pd.concat([positive_df, concept_negative_df], axis=0)
        else:
            # if not binarizing, we need to apply the chat template to the input. It becomes a standard instruction tuning task.
            if train_on_negative:
                concept_df = pd.concat([positive_df, concept_negative_df], axis=0)
            else:
                concept_df = positive_df

            if is_chat_model:
                if model_name == "meta-llama/Llama-3.1-8B-Instruct":

                    def apply_chat_template(row):
                        messages = [
                            {
                                "role": "system",
                                "content": "You are a helpful assistant.",
                            },
                            {"role": "user", "content": row["input"]},
                        ]
                        nobos = tokenizer.apply_chat_template(
                            messages,
                            tokenize=True,
                            add_generation_prompt=True,
                        )[1:]
                        return tokenizer.decode(nobos)

                    concept_df["input"] = concept_df.apply(apply_chat_template, axis=1)

                    # handling output separately.
                    def apply_chat_template_for_output(row):
                        if len(tokenizer.tokenize(row["output"])) < output_length:
                            return row["output"] + suffix_str
                        return row["output"]

                    concept_df["output"] = concept_df.apply(
                        apply_chat_template_for_output, axis=1
                    )
                else:

                    def apply_chat_template(row):
                        messages = [{"role": "user", "content": row["input"]}]
                        nobos = tokenizer.apply_chat_template(
                            messages,
                            tokenize=True,
                            add_generation_prompt=True,
                        )[1:]
                        return tokenizer.decode(nobos)

                    concept_df["input"] = concept_df.apply(apply_chat_template, axis=1)

            if train_across_concepts and not hypernet_mode:
                # Replace -1 concept ids with concept_id
                concept_df["concept_id"] = concept_df["concept_id"].replace(
                    -1, concept_id
                )

        all_dfs.append(concept_df)

    # Combine all concept dataframes
    if all_dfs:
        return pd.concat(all_dfs, axis=0, ignore_index=True)
    else:
        return pd.DataFrame()  # Return empty dataframe if no concepts processed


def save_state(dump_dir, state, concept_metadata, rank):
    dump_dir = Path(dump_dir)
    dump_dir.mkdir(parents=True, exist_ok=True)
    # Save state
    state_path = os.path.join(dump_dir, f"{STATE_FILE}_rank_{rank}")
    with open(state_path, "wb") as f:
        pickle.dump(state, f)

    # Save metadata again
    metadata_path = os.path.join(dump_dir, f"rank_{rank}_{METADATA_FILE}")
    with open(metadata_path, "a") as f:
        f.write(json.dumps(concept_metadata) + "\n")


@hydra.main(config_path="config", config_name="config", version_base=None)
def main(cfg: DictConfig):
    args = config_to_pydantic(cfg, ExperimentConfig)

    # Initialize the process group
    try:
        dist.init_process_group(backend="nccl", init_method="env://")
    except Exception as e:
        logger.error(f"Failed to initialize distributed process group: {e}")

    # Get the rank and world_size from environment variables
    rank = get_rank()
    world_size = get_world_size()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))

    # Set the device for this process
    device = get_and_set_device(local_rank)
    logger.debug(f"Using device {device}")

    # Set a unique seed per rank for reproducibility
    set_seed(args.dataset.seed + rank)

    run_name = datetime.now().strftime("train_%Y%m%d_%H%M%S%f")
    if not args.dataset.dump_dir and not args.train.debug:
        args.dataset.dump_dir = Path(args.train.save_dir) / run_name
        (args.dataset.dump_dir / "train").mkdir(parents=True, exist_ok=True)

        # Setup file logging for this training run
        if not args.train.debug:
            log_file = setup_file_logging(args.dataset.dump_dir / "logs", rank)
            logger.info(f"Logging to file: {log_file}")

    if (
        args.dataset.overwrite_metadata_dir is not None
        and Path(args.dataset.overwrite_metadata_dir).exists()
    ):
        logger.warning(f"Overwriting data directory {args.dataset.data_dir}")
        args.dataset.data_dir = args.dataset.overwrite_metadata_dir
    else:
        args.dataset.data_dir = f"{args.dataset.data_dir}/generate"

    # Load dataset and metadata
    metadata_path = os.path.join(args.dataset.data_dir, "metadata.jsonl")
    metadata = load_metadata(metadata_path)

    # if we select concepts automatically held-in
    args.dataset.held_out_eval = (
        args.dataset.held_out_eval and not args.dataset.select_concept_ids
    )

    logger.debug(f"Held out status: {args.dataset.held_out_eval}")

    held_out_concept_ids = None
    if args.dataset.eval_data_dir is not None and args.dataset.held_out_eval:
        eval_metadata = load_metadata(
            os.path.join(args.dataset.eval_data_dir, "generate", "metadata.jsonl"),
        )
        held_out_concept_ids = [int(item["concept_id"]) for item in eval_metadata]
        logger.info(
            f"Held out concept IDs: {held_out_concept_ids[0]},..., {held_out_concept_ids[-1]}",
        )

    df_generator = data_generator(
        args.dataset.data_dir,
        held_out_concept_ids=held_out_concept_ids,
        select_concept_ids=args.dataset.select_concept_ids,
    )
    all_df = pd.read_parquet(
        os.path.join(args.dataset.data_dir, "train_data.parquet"),
    )  # this is needed for binarizing the dataset
    negative_df = all_df[
        (all_df["output_concept"] == EMPTY_CONCEPT) & (all_df["category"] == "negative")
    ]
    df_list = list(df_generator)
    logger.info(f"Total number of concept df loaded: {len(df_list)}")
    if args.dataset.max_concepts:
        logger.info(
            f"All ranks only processing {min(len(df_list), args.dataset.max_concepts)} concepts",
        )
        df_list = df_list[: args.dataset.max_concepts]

    if not args.train.debug:
        OmegaConf.save(
            OmegaConf.create(args.model_dump()),
            args.dataset.dump_dir / "config.yaml",
        )

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        args.model.model_name,
        model_max_length=512,
    )
    tokenizer.padding_side = "right"

    # Load model instance onto device
    if args.train.use_bf16:
        logger.info(f"Using bfloat16 for model {args.model.model_name}")
    model_instance = AutoModelForCausalLM.from_pretrained(
        args.model.model_name,
        torch_dtype=torch.bfloat16 if args.train.use_bf16 else None,
    )
    model_instance = model_instance.eval()
    model_instance.to(device)

    configure_tokenizer_model(model_instance, tokenizer)

    # Training logic (previously in train_hypernetwork function)
    _logged_code = False
    model_config = args.model
    training_args = args.train

    logger.info(f"Training {model_config.model_name} with {len(df_list)} concepts")

    if training_args.train_on_negative:
        logger.info(f"Training {model_config.model_name} on negative examples")

    # Combine all concept data for training
    combined_df = prepare_df(
        df_list,
        negative_df,
        metadata,
        tokenizer,
        binarize=training_args.binarize_dataset,
        train_on_negative=training_args.train_on_negative,
        train_across_concepts=True,
        output_length=args.inference.output_length,
        model_name=model_config.model_name,
        max_num_of_examples=args.dataset.num_of_examples,
        hypernet_mode=True,
        replace_negative_description=True,
        negative_example_ratio=training_args.negative_example_ratio,
    )

    # Create in-train dev set
    dev_size = (
        int(args.dataset.dev_size * len(combined_df))
        if 0 < args.dataset.dev_size < 1
        else min(int(args.dataset.dev_size), len(combined_df) // 5)
    ) // world_size

    # Shuffle the dataframe before splitting
    combined_df = combined_df.sample(
        frac=1,
        random_state=training_args.seed,
    ).reset_index(drop=True)
    # Split into train and dev sets
    train_df = combined_df.iloc[dev_size:]
    dev_df = combined_df.iloc[:dev_size]

    logger.info(
        f"Training on {len(train_df)} examples, validating on {len(dev_df)} examples",
    )

    # Create model instance
    benchmark_model = get_model(
        model_config.model_name,
        model=model_instance,
        tokenizer=tokenizer,
        training_args=training_args,
        model_config=model_config,
        wandb_config=args.wandb,
        device=device,
        metadata=metadata,
        seed=training_args.seed,
        metadata_path=metadata_path,
        dump_dir=args.dataset.dump_dir / "train" if args.dataset.dump_dir else None,
    )

    benchmark_model.make_model(
        mode="train",
        low_rank_dimension=model_config.low_rank_dimension or 1,
        dtype=torch.bfloat16 if training_args.use_bf16 else None,
    )

    if training_args.use_bf16:
        benchmark_model.ax.to(torch.bfloat16)

    # Create dataloaders
    train_dataloader, train_sampler = benchmark_model.make_dataloader(
        train_df,
        rank=rank,
        world_size=world_size,
        distributed=world_size > 1,
    )

    dev_dataloader = None
    if len(dev_df) > 0:
        dev_dataloader, _ = benchmark_model.make_dataloader(
            dev_df,
            rank=rank,
            world_size=world_size,
            shuffle=False,
            distributed=world_size > 1,
        )

    # Initialize wandb
    if args.wandb.log and not training_args.debug:
        wandb.init(
            project=args.wandb.project,
            entity=args.wandb.entity,
            tags=args.wandb.tags,
            group=args.wandb.group,
            notes=args.wandb.notes,
            name=f"{model_config.model_name}_{run_name}_{df_list[-1][0]}",
            config={
                "experiment": args.model_dump(),
                "model": model_config.model_dump(),
                "training": training_args.model_dump(),
            },
        )
        if args.wandb.log_code and not _logged_code:
            wandb.run.log_code(Path(__file__).parent.parent)
            _logged_code = True

    trainer = Trainer(
        model=benchmark_model,
        training_args=training_args,
        model_config=model_config,
        wandb_config=args.wandb,
    )

    torch.cuda.empty_cache()
    trainer.train(train_dataloader, dev_dataloader, train_sampler)

    # Save model
    if rank == 0 and not training_args.debug:
        benchmark_model.save(
            args.dataset.dump_dir / "train", model_name=model_config.model_name
        )
        logger.info(f"Saved weights for model {model_config.model_name}")

    # Clean up
    del benchmark_model, trainer
    torch.cuda.empty_cache()

    destroy_process_group()

    if training_args.run_eval_suite_at_end and not training_args.debug:
        if not args.inference.factor_selection.enable:
            infer_run = run_inference(args)
            run_eval(args, infer_run=infer_run)
        else:
            run_inference(args)


if __name__ == "__main__":
    torch.autograd.set_detect_anomaly(True)
    load_dotenv()
    main()
