defaults:
  - _self_
  - dataset: base
  - model: base
  - train: base
  - inference: base
  - evaluate: base
  - generate: base
  - wandb: base
  - experiment: base  # Use base experiment by default
  - override hydra/launcher: ray_jobs
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  launcher:
    poll_jobs: false
    entrypoint_num_gpus: 1
    enable_gpu_blocking: false
    entrypoint_resources:
      axbench-main: 1
  job:
    env_set:
      OPENAI_DRY_RUN: 0
      TOKENIZERS_PARALLELISM: false
